### ISSUE TITLE
Direct edit to /etc/init/control-alt-delete.conf

### ISSUE THREAD

**Issue by jpschaaf** [fcaviggia/hardening-script-el6-kickstart#7]
It might be better to create a .override file instead of editing the /etc/init/control-alt-delete.conf file directly.  There are two reasons for that. 

1) The comment in the header indicates that the file should not be edited directly, and that an override file should be created.  

2) The text of STIG RHEL-06-000286 provides guidance to check specifically for the control-alt-delete.override file, not the .conf file.  There will probably be people blindly reading the STIG instead of configuring the system in accordance with the purpose of the STIG entry that will mark this as a finding.

My own disclaimer:  I haven't tried the override file to see if the override actually works.

**Comment by shawndwells** [comment]
On 4/10/15 5:12 PM, jpschaaf wrote:
>
> It might be better to create a .override file instead of editing the 
> /etc/init/control-alt-delete.conf file directly. There are two reasons 
> for that.
>
> 1) The comment in the header indicates that the file should not be 
> edited directly, and that an override file should be created.
>
> 2) The text of STIG RHEL-06-000286 provides guidance to check 
> specifically for the control-alt-delete.override file, not the .conf 
> file. There will probably be people blindly reading the STIG instead 
> of configuring the system in accordance with the purpose of the STIG 
> entry that will mark this as a finding.
>
> My own disclaimer: I haven't tried the override file to see if the 
> override actually works.
>

Here is the remediation script that will be published with the RHEL6 
STIG itself:
https://github.com/OpenSCAP/scap-security-guide/blob/master/RHEL/6/input/fixes/bash/disable_ctrlaltdel_reboot.sh

Highly suggest using the native remediation scripts published within 
RHEL6 and the official DISA STIG. In this way we first problems upstream :)

**Comment by fcaviggia** [comment]
True, but I'll still do both - better safe than sorry that an errant Windows admin presses Ctrl-Alt-Del to login and reboots the system.

**Comment by jpschaaf** [comment]
This was never filed against the right project anyhow -- and at this point the issue is resolved.
